# Generated by Django 6.0.6 on 2026-07-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_restockrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='stock.materialrequest'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued')], default='PENDING', max_length=10),
        ),
    ]
