# Generated by Django 5.2.3 on 2026-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_issuance_material_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
