# Generated by Django 5.2.3 on 2026-06-30 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('shop', '0003_setbreakrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='showroom_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_orders', to='shop.showroomitem'),
        ),
    ]
