# Generated by Django 5.2.3 on 2026-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_showroom_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='showroom_item',
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRICE_REVIEW', 'Price Review'), ('OPS_QUEUE', 'Ops Queue'), ('IN_PRODUCTION', 'In Production'), ('WORKSHOP_COMPLETE', 'Workshop Complete'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
