# Generated by Django 5.2.3 on 2026-07-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_showroomitem_description_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setbreakrequest',
            name='item',
        ),
        migrations.RemoveField(
            model_name='setbreakrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='setbreakrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='showroomitem',
            name='parent_set',
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='showroomitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='showroomitem',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='showroomitem',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of stock')], default='AVAILABLE', max_length=15),
        ),
        migrations.CreateModel(
            name='ShowroomItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='showroom/images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.showroomitem')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='BranchTransferRequest',
        ),
        migrations.DeleteModel(
            name='SetBreakRequest',
        ),
    ]
