# Generated by Django 5.2.3 on 2026-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_setbreakrequest_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroomitem',
            name='is_discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
