# Generated by Django 5.2.3 on 2026-07-06 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_add_branch_code'),
        ('orders', '0004_remove_order_showroom_item_order_cancellation_reason_and_more'),
        ('shop', '0008_room_itemtype_fix_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalogue/photos/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_products', to='shop.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('ref_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('within_range', models.BooleanField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_DIRECTOR', 'Pending Director'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_DIRECTOR', max_length=20)),
                ('director_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quotes', to='branches.branch')),
                ('catalogue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='shop.catalogueproduct')),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='orders.order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status'], name='shop_quote_branch__569152_idx')],
            },
        ),
    ]
