# Generated by Django 5.2.3 on 2026-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_catalogueproduct_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroomitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
